version: '3.8'

services:
  user_auth_api:
    container_name: restful_api_user_auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/restful_user_auth
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restful_user_auth
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - user_auth_api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
